name: End to end tests
on: [pull_request]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
            .next
          key: npm-${{ hashFiles('**/package-lock.json') }}
  e2e-test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
            .next
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: npm run start & npm run cy:run
